-- Generated from application question bank. Not a live backend database.
PRAGMA foreign_keys = ON;
BEGIN TRANSACTION;
CREATE TABLE chapters (id INTEGER PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE sections (id TEXT PRIMARY KEY, chapter_id INTEGER NOT NULL REFERENCES chapters(id), section_no INTEGER NOT NULL, name TEXT NOT NULL, is_review INTEGER NOT NULL CHECK(is_review IN (0,1)));
CREATE TABLE topics (id TEXT PRIMARY KEY, section_id TEXT NOT NULL REFERENCES sections(id), name TEXT NOT NULL, rule TEXT NOT NULL, method TEXT NOT NULL, pitfall TEXT NOT NULL);
CREATE TABLE questions (id TEXT PRIMARY KEY, topic_id TEXT NOT NULL REFERENCES topics(id), role TEXT NOT NULL CHECK(role IN ('example','practice')), difficulty TEXT CHECK(difficulty IN ('基础题','提高题','压轴题')), question_type TEXT NOT NULL, question_text TEXT NOT NULL, answer TEXT NOT NULL, steps_json TEXT NOT NULL, options_json TEXT NOT NULL, diagram_json TEXT);
INSERT INTO chapters VALUES (1,'三角形');
INSERT INTO sections VALUES ('1.1',1,1,'认识三角形',0);
INSERT INTO sections VALUES ('1.2',1,2,'图形的全等',0);
INSERT INTO sections VALUES ('1.3',1,3,'探索三角形全等的条件',0);
INSERT INTO sections VALUES ('1.4',1,4,'三角形的尺规作图',0);
INSERT INTO sections VALUES ('1.5',1,5,'利用三角形全等测距离',0);
INSERT INTO sections VALUES ('1.0',1,0,'单元复习',1);
INSERT INTO chapters VALUES (2,'轴对称');
INSERT INTO sections VALUES ('2.1',2,1,'轴对称现象',0);
INSERT INTO sections VALUES ('2.2',2,2,'探索轴对称的性质',0);
INSERT INTO sections VALUES ('2.3',2,3,'简单的轴对称图形',0);
INSERT INTO sections VALUES ('2.4',2,4,'利用轴对称进行设计',0);
INSERT INTO sections VALUES ('2.0',2,0,'单元复习',1);
INSERT INTO chapters VALUES (3,'勾股定理');
INSERT INTO sections VALUES ('3.1',3,1,'探索勾股定理',0);
INSERT INTO sections VALUES ('3.2',3,2,'一定是直角三角形吗',0);
INSERT INTO sections VALUES ('3.3',3,3,'勾股定理的应用举例',0);
INSERT INTO sections VALUES ('3.0',3,0,'单元复习',1);
INSERT INTO chapters VALUES (4,'实数');
INSERT INTO sections VALUES ('4.1',4,1,'无理数',0);
INSERT INTO sections VALUES ('4.2',4,2,'平方根',0);
INSERT INTO sections VALUES ('4.3',4,3,'立方根',0);
INSERT INTO sections VALUES ('4.4',4,4,'估算',0);
INSERT INTO sections VALUES ('4.5',4,5,'用计算器开方',0);
INSERT INTO sections VALUES ('4.6',4,6,'实数',0);
INSERT INTO sections VALUES ('4.0',4,0,'单元复习',1);
INSERT INTO chapters VALUES (5,'位置与坐标');
INSERT INTO sections VALUES ('5.1',5,1,'确定位置',0);
INSERT INTO sections VALUES ('5.2',5,2,'平面直角坐标系',0);
INSERT INTO sections VALUES ('5.3',5,3,'轴对称与坐标变化',0);
INSERT INTO sections VALUES ('5.0',5,0,'单元复习',1);
INSERT INTO chapters VALUES (6,'一次函数');
INSERT INTO sections VALUES ('6.1',6,1,'函数',0);
INSERT INTO sections VALUES ('6.2',6,2,'一次函数',0);
INSERT INTO sections VALUES ('6.3',6,3,'一次函数的图象',0);
INSERT INTO sections VALUES ('6.4',6,4,'确定一次函数的表达式',0);
INSERT INTO sections VALUES ('6.5',6,5,'一次函数的应用',0);
INSERT INTO sections VALUES ('6.0',6,0,'单元复习',1);
INSERT INTO topics VALUES ('t01','1.1','三边关系与第三边范围','两边为 a、b 时，第三边 c 满足 |a−b|＜c＜a+b。','先求严格范围，再结合整数、周长或等腰条件筛选。','两端不能取等号；等腰条件需区分底边和腰。');
INSERT INTO questions VALUES ('t01-example','t01','example',NULL,'解答题','三角形两边长为 4 和 7，第三边 x 为整数，求 x 的所有可能值。','4，5，6，7，8，9，10','["由三边关系，3＜x＜11。","整数 x=4，5，6，7，8，9，10，共 7 个。"]','[]',NULL);
INSERT INTO questions VALUES ('t01-1','t01','practice','基础题','选择题','下列各组线段长度中，能组成三角形的是（　）。','B','["比较较小两边之和与最大边。A、D 恰好相等，C 的和小于最大边，均不能组成三角形。","B 中 3+4＞5，能组成三角形。"]','["2，3，5","3，4，5","1，2，4","2，2，4"]',NULL);
INSERT INTO questions VALUES ('t01-2','t01','practice','提高题','填空题','三角形两边长为 5、8，第三边为偶数，则第三边共有____种可能。','5','["由三边关系，3＜x＜13。","满足条件的偶数为 4、6、8、10、12，共 5 个。"]','[]',NULL);
INSERT INTO questions VALUES ('t01-3','t01','practice','压轴题','解答题','等腰三角形周长为 20，其中一边长为 6。求所有可能的三边长。','6，6，8 或 7，7，6','["当 6 为腰时，底边为 20−12=8，6+6＞8，成立。","当 6 为底边时，两腰各为 (20−6)÷2=7，成立。","所以有两种可能。"]','[]',NULL);
INSERT INTO topics VALUES ('t02','1.1','内角和、外角与角平分线','内角和为 180°；外角等于与它不相邻的两个内角的和。','明确角所在的三角形，再列等式；角平分线对应一半角度。','外角关系不包含相邻内角。');
INSERT INTO questions VALUES ('t02-example','t02','example',NULL,'计算题','△ABC 中，∠A=48°，∠B=67°，求 ∠C。','65°','["三角形内角和为 180°。","∠C=180°−48°−67°=65°。"]','[]',NULL);
INSERT INTO questions VALUES ('t02-1','t02','practice','基础题','选择题','一个三角形的两个内角为 35°、75°，第三个内角为（　）。','C','["第三角=180°−35°−75°=70°。"]','["60°","65°","70°","110°"]',NULL);
INSERT INTO questions VALUES ('t02-2','t02','practice','提高题','计算题','△ABC 中，∠A=2∠B，C 点处的外角为 120°，求三个内角。','∠A=80°，∠B=40°，∠C=60°','["设 ∠B=x，由外角性质得 2x+x=120°，x=40°。","∠A=80°；∠C=180°−120°=60°。"]','[]',NULL);
INSERT INTO questions VALUES ('t02-3','t02','practice','压轴题','证明题','△ABC 的内角平分线 BD、CE 相交于内部点 I。若 ∠A=50°，求 ∠BIC 并说明理由。','115°','["∠ABC+∠ACB=130°。","角平分线给出 ∠IBC+∠ICB=65°。","在 △BIC 中，∠BIC=180°−65°=115°。"]','[]',NULL);
INSERT INTO topics VALUES ('t03','1.1','中线、高与面积分割','中线连接顶点与对边中点；高是顶点到对边所在直线的垂线段。','面积比较先找同高或同底关系，用底边比转化为面积比。','高可能在三角形外；中线通常不是高。');
INSERT INTO questions VALUES ('t03-example','t03','example',NULL,'解答题','△ABC 面积为 24，AD 是中线，求 △ABD 面积。','12','["BD=DC，两三角形到 BC 的高相同，所以面积相等。","△ABD 面积=24÷2=12。"]','[]','{"points":{"A":[4,6],"B":[0,0,-16,16],"C":[8,0,6,16],"D":[4,0,6,16]},"lines":[["A","B"],["B","C"],["C","A"],["A","D"]],"label":"三角形 ABC，D 为底边 BC 的中点"}');
INSERT INTO questions VALUES ('t03-1','t03','practice','基础题','填空题','△ABC 中 AD 是中线，BC=14，则 BD=____。','7','["D 是 BC 中点，BD=14÷2=7。"]','[]',NULL);
INSERT INTO questions VALUES ('t03-2','t03','practice','提高题','解答题','D 在线段 BC 上，BD∶DC=2∶3，△ABC 面积为 40，求 △ABD、△ACD 的面积。','16；24','["同高三角形面积比等于底边比，即 2∶3。","面积分别为 40×2/5=16 和 40×3/5=24。"]','[]',NULL);
INSERT INTO questions VALUES ('t03-3','t03','practice','压轴题','解答题','△ABC 面积为 48，D 为 BC 中点，E 为 AD 中点，求 △BDE 与 △BEC 的面积。','12；24','["AD 将 △ABC 的面积平分，△BDA 面积为 24。","以 AD 为底比较，DE=AD/2，所以 △BDE 面积为 12；同理 △CDE 面积为 12。","△BEC 面积=12+12=24。"]','[]','{"points":{"A":[4,6],"B":[0,0,-16,16],"C":[8,0,6,16],"D":[4,0,6,16],"E":[4,3]},"lines":[["A","B"],["B","C"],["C","A"],["A","D"],["B","E"],["C","E"]],"label":"三角形 ABC，D 为底边 BC 的中点"}');
INSERT INTO topics VALUES ('t04','1.2','全等图形的对应关系','全等三角形的对应边、对应角分别相等。','按全等符号中的顶点顺序写出对应关系，再求值。','不能只凭摆放方向找对应边。');
INSERT INTO questions VALUES ('t04-example','t04','example',NULL,'填空题','△ABC≌△DEF，AB=6，∠C=48°，求 DE、∠F。','6；48°','["A↔D，B↔E，C↔F。","AB 对应 DE，∠C 对应 ∠F，所以 DE=6，∠F=48°。"]','[]',NULL);
INSERT INTO questions VALUES ('t04-1','t04','practice','基础题','选择题','△ABC≌△PQR，AC 的对应边是（　）。','B','["A↔P，C↔R，所以 AC 对应 PR。"]','["PQ","PR","QR","不能确定"]',NULL);
INSERT INTO questions VALUES ('t04-2','t04','practice','提高题','计算题','△ABC≌△DEF，AB=2x+1，DE=11，BC=9，CA=7，求 x 和 △DEF 的周长。','x=5，周长 27','["2x+1=11，得 x=5。","全等三角形周长相等，周长=11+9+7=27。"]','[]',NULL);
INSERT INTO questions VALUES ('t04-3','t04','practice','压轴题','解答题','△ABC≌△DEF，∠A=(2x+10)°，∠D=(3x−20)°，∠B=∠F，求各角。','∠A=∠D=70°，其余四角均为 55°','["2x+10=3x−20，x=30，所以 ∠A=∠D=70°。","∠F=∠C，结合 ∠B=∠F 得 ∠B=∠C。","∠B=∠C=(180°−70°)÷2=55°，对应角同样为 55°。"]','[]',NULL);
INSERT INTO topics VALUES ('t05','1.3','SSS、SAS 与全等条件补充','SSS：三边对应相等；SAS：两边及其夹角对应相等。','列出已知条件，寻找公共边、对顶角或公共角。','SAS 的角必须是夹角；SSA 不能一般性判定全等。');
INSERT INTO questions VALUES ('t05-example','t05','example',NULL,'证明题','四边形 ABCD 中 AB=AD，BC=DC。连接 AC，证明 △ABC≌△ADC。','△ABC≌△ADC（SSS）','["AB=AD，BC=DC，AC 为公共边。","三组对应边相等，所以 △ABC≌△ADC（SSS）。"]','[]',NULL);
INSERT INTO questions VALUES ('t05-1','t05','practice','基础题','选择题','AB=DE、AC=DF，补充哪项可用 SAS 判定 △ABC≌△DEF？','A','["AB、AC 的夹角是 ∠A；DE、DF 的夹角是 ∠D。"]','["∠A=∠D","∠B=∠E","∠C=∠F","∠B=∠F"]',NULL);
INSERT INTO questions VALUES ('t05-2','t05','practice','提高题','证明题','线段 AB、CD 相交于 O，OA=OB，OC=OD，证明 AC=BD。','AC=BD','["∠AOC=∠BOD（对顶角），OA=OB，OC=OD。","△AOC≌△BOD（SAS），对应边 AC=BD。"]','[]','{"points":{"A":[1,5],"B":[7,1],"C":[2,0,-15,15],"D":[6,6],"O":[4,3]},"lines":[["A","B"],["C","D"],["A","C"],["B","D"]],"label":"AB、CD 相交于 O，OA=OB，OC=OD"}');
INSERT INTO questions VALUES ('t05-3','t05','practice','压轴题','证明题','△ABC 中 AB=AC，D、E 分别在线段 AB、AC 上，AD=AE。证明 BE=CD。','BE=CD','["比较 △ABE 与 △ACD：AB=AC，AE=AD。","∠BAE=∠CAD=∠BAC，为两组对应边的夹角。","△ABE≌△ACD（SAS），故 BE=CD。"]','[]',NULL);
INSERT INTO topics VALUES ('t06','1.3','ASA、AAS 与直角三角形全等','两角及夹边相等可用 ASA；两角及一角对边相等可用 AAS；直角三角形可用 HL。','识别公共边与平行线导出的角；使用 HL 前写明直角前提。','只有两角相等不足以推出全等。');
INSERT INTO questions VALUES ('t06-example','t06','example',NULL,'证明题','△ABC 与 △DEF 中，∠B=∠E、∠C=∠F、BC=EF，说明全等理由。','△ABC≌△DEF（ASA）','["BC、EF 分别是两组相等角的夹边。","两角及夹边对应相等，故由 ASA 判定全等。"]','[]',NULL);
INSERT INTO questions VALUES ('t06-1','t06','practice','基础题','选择题','两直角三角形的斜边和一条直角边分别相等，可用（　）判定全等。','C','["在直角三角形前提下，斜边和直角边分别相等满足 HL。"]','["AAA","SSA","HL","不能判定"]',NULL);
INSERT INTO questions VALUES ('t06-2','t06','practice','提高题','证明题','AD⊥BC，D 在 BC 上，AB=AC，证明 BD=CD。','BD=CD','["△ABD、△ACD 都是直角三角形。","斜边 AB=AC，直角边 AD 公共。","由 HL 得 △ABD≌△ACD，所以 BD=CD。"]','[]','{"points":{"A":[4,6],"B":[0,0,-16,16],"C":[8,0,6,16],"D":[4,0,6,16]},"lines":[["A","B"],["B","C"],["C","A"],["A","D"]],"label":"三角形 ABC，D 为底边 BC 的中点"}');
INSERT INTO questions VALUES ('t06-3','t06','practice','压轴题','证明题','四边形 ABCD 中 AB∥CD，AD∥BC，连接 AC。证明 AB=CD，AD=BC。','AB=CD，AD=BC','["由平行线得 ∠BAC=∠DCA，∠BCA=∠DAC。","AC 为公共边，由 ASA 得 △BAC≌△DCA。","对应边相等，AB=CD，BC=DA。"]','[]',NULL);
INSERT INTO topics VALUES ('t07','1.4','尺规作图与作图依据','用无刻度直尺与圆规，根据给定边角条件定位第三顶点。','分析距离条件，用两弧交点定位，保留作图痕迹。','三边不满足三边关系时无法作出三角形。');
INSERT INTO questions VALUES ('t07-example','t07','example',NULL,'作图题','已知三条线段长为 3、4、5，写出尺规作三角形的步骤。','以 5 为底，用半径 3、4 的弧定位第三顶点','["作 AB=5。","以 A、B 为圆心，以 3、4 为半径作弧，交于 C。","连接 AC、BC。SSS 保证所得三角形满足条件。"]','[]',NULL);
INSERT INTO questions VALUES ('t07-1','t07','practice','基础题','选择题','尺规作图中的无刻度直尺用于（　）。','B','["无刻度直尺用来画直线、射线或线段；转移长度使用圆规。"]','["读取长度","画直线或线段","测量角度","直接读取中点"]',NULL);
INSERT INTO questions VALUES ('t07-2','t07','practice','提高题','作图题','已知线段 AB，写出作其垂直平分线的尺规步骤。','连接两组等半径弧的交点','["分别以 A、B 为圆心，以同一大于 AB 一半的长度为半径，在 AB 两侧作弧，交于 P、Q。","连接 PQ。P、Q 均到 A、B 等距，所以 PQ 是 AB 的垂直平分线。"]','[]',NULL);
INSERT INTO questions VALUES ('t07-3','t07','practice','压轴题','解答题','用长为 4、7、c 的三条线段作三角形。分别讨论 c=3、5、11 时能否作成，并解释。','只有 c=5 可以','["第三边应满足 3＜c＜11。","c=5 满足，可作出两个关于底边对称的全等三角形。","c=3 或 11 时三点共线，两边之和等于第三边，不能作成非退化三角形。"]','[]',NULL);
INSERT INTO topics VALUES ('t08','1.5','利用全等测量不可达距离','构造全等三角形，将不可到达的线段转移为可测量的对应边。','确定目标边的对应边，再证明全等。','结论依赖构造条件，不能凭示意图猜等长。');
INSERT INTO questions VALUES ('t08-example','t08','example',NULL,'解答题','AB、CD 相交于 O，OA=OB，OC=OD，测得 BD=18 米，求 AC。','18 米','["对顶角 ∠AOC=∠BOD，且 OA=OB，OC=OD。","△AOC≌△BOD（SAS），AC=BD=18 米。"]','[]',NULL);
INSERT INTO questions VALUES ('t08-1','t08','practice','基础题','填空题','已证明 △ABC≌△DEF，河宽 AB 对应 DE，DE=24 米，则河宽为____米。','24','["全等三角形对应边相等，AB=DE=24 米。"]','[]',NULL);
INSERT INTO questions VALUES ('t08-2','t08','practice','提高题','证明题','AB、CD 相交于 O，OA=OB，AC∥BD，证明 OC=OD。','OC=OD','["对顶角 ∠AOC=∠BOD；平行线给出 ∠OAC=∠OBD。","结合 OA=OB，由 ASA 得 △AOC≌△BOD。","所以 OC=OD。"]','[]',NULL);
INSERT INTO questions VALUES ('t08-3','t08','practice','压轴题','解答题','AB、CD 相交于 O，OA=OB，AC∥BD，实测 BD=32 米。求 AC；若删去平行条件，能否仍确定 AC？','原方案 AC=32 米；删去平行条件后不能确定','["由平行线和对顶角得两组角相等，结合 OA=OB，用 ASA 证明 △AOC≌△BOD。","因此 AC=BD=32 米。","仅保留一组边和一组角相等不足以判定全等，移动 C 可改变 AC。"]','[]',NULL);
INSERT INTO topics VALUES ('t09','2.1','轴对称图形与对称轴','沿某直线折叠后两侧完全重合的图形是轴对称图形，该直线是对称轴。','想象折叠后的重合关系，逐条检查对称轴。','对称轴是直线；两个图形成轴对称与一个轴对称图形应区分。');
INSERT INTO questions VALUES ('t09-example','t09','example',NULL,'解答题','长方形不是正方形时，有几条对称轴？分别是什么？','2 条','["过两组对边中点的直线分别能使两侧重合。","对角线不能使非正方形的长方形两侧重合，故只有 2 条。"]','[]',NULL);
INSERT INTO questions VALUES ('t09-1','t09','practice','基础题','选择题','正方形有几条对称轴？','C','["两条对角线和两条连接对边中点的直线，共 4 条。"]','["1","2","4","无数条"]',NULL);
INSERT INTO questions VALUES ('t09-2','t09','practice','提高题','填空题','一个等腰但非等边三角形有____条对称轴；圆有____条对称轴。','1；无数','["等腰三角形只有顶角平分线所在直线为对称轴。","圆的每条直径所在直线都是对称轴，故有无数条。"]','[]',NULL);
INSERT INTO questions VALUES ('t09-3','t09','practice','压轴题','解答题','一个三角形若有两条不同的对称轴，说明它是什么三角形，并求其全部对称轴数量。','等边三角形，有 3 条对称轴','["三角形的每条对称轴都经过一个顶点与对边中点，且该顶点两侧的边相等。","两条不同对称轴带来两组等边关系，故三边相等。","等边三角形的三个顶角平分线所在直线都是对称轴，共 3 条。"]','[]',NULL);
INSERT INTO topics VALUES ('t10','2.2','对称点作图与垂直平分','对称轴垂直平分每一对对应点的连线；轴上的点与自身对应。','从原点向对称轴作垂线，在另一侧截取相等距离。','对称点连线必须与轴垂直，不能沿任意方向量距离。');
INSERT INTO questions VALUES ('t10-example','t10','example',NULL,'作图题','点 P 在直线 l 外，说明如何作它关于 l 的对称点 P′。','垂足另一侧取等距点','["过 P 作 PH⊥l，垂足为 H。","在直线 PH 上、H 的另一侧取 P′，使 HP′=HP。","l 垂直平分 PP′，所以 P′ 是所求点。"]','[]',NULL);
INSERT INTO questions VALUES ('t10-1','t10','practice','基础题','填空题','P、P′ 关于直线 l 对称，PP′=12，则 P 到 l 的距离为____。','6','["l 垂直平分 PP′，距离为 PP′÷2=6。"]','[]',NULL);
INSERT INTO questions VALUES ('t10-2','t10','practice','提高题','作图题','△ABC 中 A 在对称轴 l 上，B、C 在 l 同侧。说明作其对称三角形的步骤，并指出哪些点不动。','A 不动；分别作 B′、C′，连接 AB′、B′C′、C′A','["轴上的 A 与自身重合。","从 B、C 向 l 作垂线，分别在另一侧截取等长得到 B′、C′。","连接对应顶点，所得 △AB′C′ 与 △ABC 关于 l 对称。"]','[]',NULL);
INSERT INTO questions VALUES ('t10-3','t10','practice','压轴题','证明题','A、B 关于直线 l 对称，P、Q 均在 l 上，且 P≠Q。证明 △APQ≌△BPQ。','△APQ≌△BPQ（SSS）','["l 为 AB 的垂直平分线，所以 PA=PB、QA=QB。","PQ 为公共边。","三边分别对应相等，故 △APQ≌△BPQ（SSS）。"]','[]',NULL);
INSERT INTO topics VALUES ('t11','2.3','线段垂直平分线的性质与判定','垂直平分线上的点到两端点等距；到两端点等距的点在线段垂直平分线上。','在几何位置与等距条件之间转换，必要时建立方程。','等距是到两个端点的距离相等，不是到任意两条边等距。');
INSERT INTO questions VALUES ('t11-example','t11','example',NULL,'计算题','P 在 AB 的垂直平分线上，PA=2x+1，PB=11，求 x。','5','["PA=PB，故 2x+1=11。","解得 x=5。"]','[]',NULL);
INSERT INTO questions VALUES ('t11-1','t11','practice','基础题','填空题','P 在 AB 的垂直平分线上，PA=9，则 PB=____。','9','["P 到 A、B 的距离相等，PB=PA=9。"]','[]',NULL);
INSERT INTO questions VALUES ('t11-2','t11','practice','提高题','证明题','PA=PB，QA=QB，P≠Q，证明 PQ⊥AB。','PQ⊥AB','["P、Q 都到 A、B 等距，所以都在 AB 的垂直平分线上。","过两点只有一条直线，PQ 就是该垂直平分线，故 PQ⊥AB。"]','[]',NULL);
INSERT INTO questions VALUES ('t11-3','t11','practice','压轴题','证明题','△ABC 中，O 为 AB 与 AC 的垂直平分线的交点。证明 O 也在 BC 的垂直平分线上。','O 在 BC 的垂直平分线上','["由第一条垂直平分线得 OA=OB。","由第二条得 OA=OC，所以 OB=OC。","到 B、C 等距的点在 BC 的垂直平分线上，结论成立。"]','[]',NULL);
INSERT INTO topics VALUES ('t12','2.3','角平分线与到两边的距离','角平分线上的点到角两边的距离相等；角内部到两边距离相等的点在角平分线上。','先作垂线确认距离，再运用性质或 HL 证明。','点到边的距离必须取垂线段，不能取斜线段。');
INSERT INTO questions VALUES ('t12-example','t12','example',NULL,'解答题','OP 平分 ∠AOB，PM⊥OA、PN⊥OB，PM=5，求 PN。','5','["P 在角平分线上，PM、PN 分别是到角两边的距离。","所以 PN=PM=5。"]','[]',NULL);
INSERT INTO questions VALUES ('t12-1','t12','practice','基础题','填空题','P 在 ∠AOB 内部，P 到 OA、OB 的距离都是 3，则 OP____∠AOB。','平分','["角内部到两边距离相等的点在角平分线上。"]','[]',NULL);
INSERT INTO questions VALUES ('t12-2','t12','practice','提高题','计算题','P 在一个角的平分线上，到两边的距离分别为 3x−2、x+6，求这两个距离。','均为 10','["距离相等，3x−2=x+6，所以 x=4。","距离为 3×4−2=10。"]','[]',NULL);
INSERT INTO questions VALUES ('t12-3','t12','practice','压轴题','证明题','I 为 △ABC 的 ∠A、∠B 的内部角平分线交点。证明 CI 平分 ∠C。','CI 平分 ∠C','["由 ∠A 的角平分线性质，I 到 AB、AC 的距离相等。","由 ∠B 的角平分线性质，I 到 AB、BC 的距离相等。","因此 I 到 AC、BC 的距离相等；I 在 ∠C 内部，所以 CI 平分 ∠C。"]','[]',NULL);
INSERT INTO topics VALUES ('t13','2.3','等腰三角形的性质与分类讨论','等腰三角形两底角相等，顶角平分线、底边中线与底边高重合。','角度题区分已知角是顶角还是底角；边长题区分腰与底边。','分类后检查内角和或三边关系，舍去不成立情形。');
INSERT INTO questions VALUES ('t13-example','t13','example',NULL,'计算题','等腰三角形顶角为 40°，求两个底角。','均为 70°','["两底角相等，总和为 180°−40°=140°。","每个底角为 70°。"]','[]',NULL);
INSERT INTO questions VALUES ('t13-1','t13','practice','基础题','填空题','等腰三角形一个底角为 52°，则顶角为____。','76°','["顶角=180°−52°×2=76°。"]','[]',NULL);
INSERT INTO questions VALUES ('t13-2','t13','practice','提高题','计算题','等腰三角形有一个角为 40°，求所有可能的三内角。','40°、70°、70°；100°、40°、40°','["若 40° 是顶角，两底角均为 70°。","若 40° 是底角，顶角为 180°−80°=100°。"]','[]',NULL);
INSERT INTO questions VALUES ('t13-3','t13','practice','压轴题','证明题','△ABC 中 AB=AC，D 是 BC 中点，E 在 AD 上。证明 EB=EC。','EB=EC','["由等腰三角形三线合一，AD 是 BC 的垂直平分线。","E 在垂直平分线上，到 B、C 等距，所以 EB=EC。","也可用 △BDE≌△CDE（SAS）证明。"]','[]','{"points":{"A":[4,6],"B":[0,0,-16,16],"C":[8,0,6,16],"D":[4,0,6,16],"E":[4,2]},"lines":[["A","B"],["B","C"],["C","A"],["A","D"],["B","E"],["C","E"]],"label":"三角形 ABC，D 为底边 BC 的中点"}');
INSERT INTO topics VALUES ('t14','2.3','等边三角形与 30° 直角三角形','等边三角形三角均为 60°；直角三角形中，30° 角所对直角边为斜边的一半。','把等边三角形沿高分成两个直角三角形，再找 30° 对边。','一半关系对应 30° 的对边，不能误用在邻边上。');
INSERT INTO questions VALUES ('t14-example','t14','example',NULL,'计算题','直角三角形中，一个锐角为 30°，斜边长为 12，求 30° 所对的边。','6','["30° 所对直角边等于斜边的一半。","所求边长=12÷2=6。"]','[]',NULL);
INSERT INTO questions VALUES ('t14-1','t14','practice','基础题','填空题','等边三角形一个内角为____。','60°','["三角相等且和为 180°，每个角为 60°。"]','[]',NULL);
INSERT INTO questions VALUES ('t14-2','t14','practice','提高题','计算题','△ABC 中 ∠C=90°、∠A=30°，BC=7，求 AB 及 ∠B。','AB=14，∠B=60°','["BC 对着 30°，所以 AB=2BC=14。","∠B=180°−90°−30°=60°。"]','[]',NULL);
INSERT INTO questions VALUES ('t14-3','t14','practice','压轴题','证明题','等边 △ABC 中，D 是 BC 中点，E 在 AC 上且 BE⊥AC。证明 AD=BE。','AD=BE','["等边三角形中，AD⊥BC 且 ∠CAD=30°。BE⊥AC，两个三角形 △ACD、△BAE 都是直角三角形。","它们的斜边 AC=BA，∠ACD=∠BAE=60°。","由 AAS 判定 △ACD≌△BAE，因此 AD=BE。"]','[]',NULL);
INSERT INTO topics VALUES ('t15','2.4','利用轴对称设计与最短路径','轴对称保持长度和角度；借助对称点把折线路径转成直线路径。','先作对称点，连接，再取连线与对称轴的交点。','最短路径需要交点位于允许行走的直线上或指定区间内。');
INSERT INTO questions VALUES ('t15-example','t15','example',NULL,'作图题','在直线 l 一侧有 A、B 两点，在线 l 上选 P，使 PA+PB 最小，写出作图方法。','作 A 的对称点 A′，取 A′B 与 l 的交点 P','["作 A 关于 l 的对称点 A′。","连接 A′B，交 l 于 P。","PA=PA′，于是 PA+PB=PA′+PB≥A′B；三点共线时取等号。"]','[]',NULL);
INSERT INTO questions VALUES ('t15-1','t15','practice','基础题','选择题','关于直线作轴对称变换后，一条长 8 的线段的对应线段长为（　）。','B','["轴对称保持长度，所以对应线段长仍为 8。"]','["4","8","16","无法确定"]',NULL);
INSERT INTO questions VALUES ('t15-2','t15','practice','提高题','作图题','设计一个关于水平直线 l 对称的折线图案：l 上有 A，l 上方有 B、C。说明如何由折线 ABC 补出对称部分。','作 B′、C′，连接 AB′C′','["A 在轴上不动。","分别作 B、C 关于 l 的对称点 B′、C′。","连接 AB′、B′C′，与原折线共同组成所需图案。"]','[]',NULL);
INSERT INTO questions VALUES ('t15-3','t15','practice','压轴题','解答题','直线 l 同侧有 A、B，A′ 为 A 关于 l 的对称点，A′B=13。若 A′B 与 l 交于 P，求 PA+PB 的最小值，并解释为什么其他点不能更小。','13','["对任意 Q∈l，QA=QA′，故 QA+QB=QA′+QB。","由两点之间线段最短，QA′+QB≥A′B=13。","在 P 处 A′、P、B 共线，等号成立，因此最小值为 13。"]','[]',NULL);
INSERT INTO topics VALUES ('t16','3.1','勾股定理求边与面积','直角三角形两直角边 a、b 与斜边 c 满足 a²+b²=c²。','先找直角和斜边，再代入；求直角边时用平方差。','最长边才可能是斜边，未知边长取正值。');
INSERT INTO questions VALUES ('t16-example','t16','example',NULL,'计算题','直角三角形两直角边为 6、8，求斜边与面积。','斜边 10，面积 24','["c²=6²+8²=100，c=10。","面积=6×8÷2=24。"]','[]','{"points":{"A":[0,6,-15,-8],"B":[8,0,6,16],"C":[0,0,-15,16]},"lines":[["A","B"],["B","C"],["C","A"]],"bounds":[-1,9,-1,7],"label":"直角三角形 ABC，C 为直角顶点"}');
INSERT INTO questions VALUES ('t16-1','t16','practice','基础题','填空题','直角三角形斜边为 13，一条直角边为 5，另一条直角边为____。','12','["b²=13²−5²=144，边长 b=12。"]','[]',NULL);
INSERT INTO questions VALUES ('t16-2','t16','practice','提高题','计算题','直角三角形两直角边之比为 3∶4，斜边为 20，求两直角边及面积。','12，16；面积 96','["设两直角边为 3k、4k，则 9k²+16k²=400。","k>0，得 k=4，所以两边为 12、16。","面积=12×16÷2=96。"]','[]',NULL);
INSERT INTO questions VALUES ('t16-3','t16','practice','压轴题','解答题','直角三角形一条直角边为 8，斜边比另一条直角边长 2，求三边及面积。','8、15、17；面积 60','["设另一条直角边为 x，斜边为 x+2。","8²+x²=(x+2)²，化简得 64=4x+4，x=15。","斜边=17，面积=8×15÷2=60。"]','[]',NULL);
INSERT INTO topics VALUES ('t17','3.1','勾股定理中的分类与分割','直角三角形的已知边若未说明位置，要讨论斜边与直角边。','按最大边位置分类；复杂图形作高拆成直角三角形。','不能默认两个已知边都是直角边。');
INSERT INTO questions VALUES ('t17-example','t17','example',NULL,'解答题','直角三角形两边长为 3、5，求第三边。','4 或 √34','["若 5 为斜边，第三边=√(25−9)=4。","若 3、5 都为直角边，第三边=√(9+25)=√34。","3 不可能是斜边，因为已有更长边 5。"]','[]',NULL);
INSERT INTO questions VALUES ('t17-1','t17','practice','基础题','选择题','直角三角形中，两直角边均为 1，斜边为（　）。','B','["斜边平方=1+1=2，斜边为 √2。"]','["1","√2","2","√3"]',NULL);
INSERT INTO questions VALUES ('t17-2','t17','practice','提高题','计算题','等腰三角形腰为 13，底边为 10，求底边上的高和面积。','高 12，面积 60','["高平分底边，半底长为 5。","高 h=√(13²−5²)=12。","面积=10×12÷2=60。"]','[]',NULL);
INSERT INTO questions VALUES ('t17-3','t17','practice','压轴题','解答题','△ABC 中 AB=13、AC=15、BC=14。高 AD 的垂足 D 在线段 BC 上。求 BD、AD 和面积。','BD=5，AD=12，面积 84','["设 BD=x，DC=14−x，高为 h。","由勾股定理，x²+h²=169，(14−x)²+h²=225。","相减得 196−28x=56，x=5，h²=169−25=144，所以 h=12。","面积=14×12÷2=84。"]','[]',NULL);
INSERT INTO topics VALUES ('t18','3.2','勾股定理的逆定理','若三边中最长边 c 满足 a²+b²=c²，则三角形为直角三角形。','先确定最大边，计算两小边平方和，再与最大边平方比较。','必须用最大边检验，边长关系不能写成两边和等于第三边。');
INSERT INTO questions VALUES ('t18-example','t18','example',NULL,'解答题','边长为 7、24、25 的三角形是直角三角形吗？','是','["最大边为 25。","7²+24²=49+576=625=25²，由勾股定理逆定理可知是直角三角形。"]','[]',NULL);
INSERT INTO questions VALUES ('t18-1','t18','practice','基础题','选择题','下列哪组是直角三角形的三边？','B','["8²+15²=64+225=289=17²。其余各组不满足。"]','["4，5，6","8，15，17","5，6，7","6，7，8"]',NULL);
INSERT INTO questions VALUES ('t18-2','t18','practice','提高题','解答题','△ABC 三边满足 a∶b∶c=5∶12∶13，周长为 60。判断形状并求面积。','直角三角形，面积 120','["比例总份数为 30，比例系数为 60÷30=2，三边为 10、24、26。","10²+24²=26²，所以是直角三角形。","面积=10×24÷2=120。"]','[]',NULL);
INSERT INTO questions VALUES ('t18-3','t18','practice','压轴题','解答题','三条线段长为 n、n+1、n+2，其中 n 为正整数。若能组成直角三角形，求 n。','n=3','["最大边为 n+2，故 n²+(n+1)²=(n+2)²。","化简得 n²−2n−3=0，即 (n−3)(n+1)=0。","n 为正整数，得 n=3；3、4、5 满足三边关系。"]','[]',NULL);
INSERT INTO topics VALUES ('t19','3.3','梯子、折断与实际距离','把墙、地面或竖直物体形成的直角关系转化为直角三角形。','明确总长是否保持不变，设所求量并用勾股定理。','水平移动距离不等于竖直下降距离。');
INSERT INTO questions VALUES ('t19-example','t19','example',NULL,'解答题','长 10 米的梯子靠墙，梯脚离墙 6 米，求梯顶离地高度。','8 米','["墙与地面垂直，梯子为斜边。","高度=√(10²−6²)=8 米。"]','[]',NULL);
INSERT INTO questions VALUES ('t19-1','t19','practice','基础题','填空题','长 13 米的梯子靠墙，梯脚距墙 5 米，则梯顶离地____米。','12','["高度平方=169−25=144，所以高度为 12 米。"]','[]',NULL);
INSERT INTO questions VALUES ('t19-2','t19','practice','提高题','解答题','一根 10 米长的杆折断后，杆顶触地处距底端 4 米。折断点距地面多高？','4.2 米','["设高度为 x，则折下部分长 10−x，为斜边。","x²+4²=(10−x)²，得 16=100−20x。","x=4.2，折下部分为 5.8 米，符合题意。"]','[]',NULL);
INSERT INTO questions VALUES ('t19-3','t19','practice','压轴题','解答题','长 10 米的梯子，初始梯脚离墙 6 米；梯脚向外移动 2 米后，梯顶下降多少米？','2 米','["初始高度=√(100−36)=8 米。","移动后梯脚距墙 8 米，高度=√(100−64)=6 米。","下降高度=8−6=2 米。本题恰好与水平移动相同，但一般不相同。"]','[]',NULL);
INSERT INTO topics VALUES ('t20','3.3','展开图中的最短路径','沿物体表面行走的路径，可将指定表面展开，用两点间线段最短求解。','先确定允许经过的表面，再展开；有多种展开方式时逐一比较。','不能用穿过物体内部的空间线段替代表面路径。');
INSERT INTO questions VALUES ('t20-example','t20','example',NULL,'解答题','长方体长、宽、高分别为 4、3、2。路线限定经过前面（4×2）和右面（3×2），从展开图一角到对角的最短路径为多少？','√53','["两相邻面展开成长 4+3=7、高 2 的长方形。","最短路径是对角线，长为 √(7²+2²)=√53。"]','[]',NULL);
INSERT INTO questions VALUES ('t20-1','t20','practice','基础题','计算题','长方形长 12、宽 5，求连接两对角顶点的最短距离。','13','["两点间线段最短，对角线为所求。","长=√(12²+5²)=13。"]','[]',NULL);
INSERT INTO questions VALUES ('t20-2','t20','practice','提高题','解答题','圆柱侧面展开后的宽（底面周长）为 12、高为 9。从下底一点沿侧面恰好绕一周到其正上方的上底点，最短路程是多少？','15','["展开一周后，起终点的水平距离为 12，竖直距离为 9。","直线最短，路程=√(12²+9²)=15。"]','[]',NULL);
INSERT INTO questions VALUES ('t20-3','t20','practice','压轴题','解答题','长方体长、宽、高为 6、3、2，求沿表面从一个顶点到与其相对顶点的最短距离。比较三种相邻面展开方案。','√61','["将两种边合并为展开面的宽，有三种候选距离。","分别为 √((6+3)²+2²)=√85，√((6+2)²+3²)=√73，√((3+2)²+6²)=√61。","三种路线都能沿相邻表面实现，最小为 √61。"]','[]',NULL);
INSERT INTO topics VALUES ('t21','4.1','无理数识别与分类','无理数是无限不循环小数；有理数包括整数、分数和有限或无限循环小数。','先化简根式，再判断是否可写成两个整数之比。','带根号不一定是无理数；无限小数不一定是无理数。');
INSERT INTO questions VALUES ('t21-example','t21','example',NULL,'解答题','在 √9、√2、0.125、π、0.333…（3 循环）中找出无理数。','√2、π','["√9=3，0.125=1/8，0.333…=1/3，都是有理数。","√2、π 是无限不循环小数，为无理数。"]','[]',NULL);
INSERT INTO questions VALUES ('t21-1','t21','practice','基础题','选择题','下列数中是无理数的是（　）。','C','["√16=4，−2/3 和 0.25 都是有理数；√7 是无理数。"]','["√16","−2/3","√7","0.25"]',NULL);
INSERT INTO questions VALUES ('t21-2','t21','practice','提高题','填空题','在 −√25、√3、22/7、π−1、0.1010010001…（相邻 1 之间的 0 依次增加）中，无理数有____个。','3','["−√25=−5、22/7 是有理数。","√3、π−1 和所给无限不循环小数是无理数，共 3 个。"]','[]',NULL);
INSERT INTO questions VALUES ('t21-3','t21','practice','压轴题','解答题','分别举例说明：两个无理数的和可以是有理数，也可以是无理数；积也可以是有理数。','例如 √2+(−√2)=0；√2+√2=2√2；√2×√2=2','["√2 与 −√2 都是无理数，和为有理数 0。","√2 与 √2 的和为 2√2，是无理数。","两者相乘为 2，是有理数。因此不能只根据参与运算的数的类别判断结果。"]','[]',NULL);
INSERT INTO topics VALUES ('t22','4.2','平方根与算术平方根','若 x²=a，x 是 a 的平方根；非负平方根 √a 是 a 的算术平方根。','看到“平方根”考虑正负两个；看到 √a 只取非负值。','正数有两个平方根；0 只有一个；负数没有实数平方根。');
INSERT INTO questions VALUES ('t22-example','t22','example',NULL,'计算题','求 49 的平方根和算术平方根。','平方根 ±7；算术平方根 7','["因为 7²=49、(−7)²=49，平方根为 ±7。","其中非负的 7 是算术平方根，√49=7。"]','[]',NULL);
INSERT INTO questions VALUES ('t22-1','t22','practice','基础题','选择题','√81 的值为（　）。','B','["根号表示算术平方根，故 √81=9。"]','["±9","9","−9","81"]',NULL);
INSERT INTO questions VALUES ('t22-2','t22','practice','提高题','计算题','解方程 (x−2)²=25。','x=7 或 −3','["x−2 是 25 的平方根，所以 x−2=5 或 −5。","分别得 x=7 或 x=−3。"]','[]',NULL);
INSERT INTO questions VALUES ('t22-3','t22','practice','压轴题','解答题','一个正数的两个平方根分别为 2a−1 与 a−5，求 a 和这个正数。','a=2，正数为 9','["两个平方根互为相反数，(2a−1)+(a−5)=0。","3a−6=0，a=2，此时两根为 3、−3。","原数为 3²=9。"]','[]',NULL);
INSERT INTO topics VALUES ('t23','4.2','根号的非负性与 √(a²)','根号内必须非负；√(a²)=|a|，结果总不小于 0。','先确定 a 的正负，再去绝对值；非负数之和为零时各项为零。','√(a²) 不总等于 a，例如 a=−3 时结果为 3。');
INSERT INTO questions VALUES ('t23-example','t23','example',NULL,'计算题','计算 √((−6)²)。','6','["√((−6)²)=|−6|=6。"]','[]',NULL);
INSERT INTO questions VALUES ('t23-1','t23','practice','基础题','填空题','式子 √(x−3) 在实数范围内有意义时，x 的取值范围为____。','x≥3','["被开方数不小于 0，所以 x−3≥0，得 x≥3。"]','[]',NULL);
INSERT INTO questions VALUES ('t23-2','t23','practice','提高题','计算题','已知 a＜2，化简 √((a−2)²)。','2−a','["√((a−2)²)=|a−2|。","a＜2，所以 a−2＜0，绝对值为 2−a。"]','[]',NULL);
INSERT INTO questions VALUES ('t23-3','t23','practice','压轴题','解答题','已知 √(x−2)+(y+3)²=0，求 x、y 及 x−y。','x=2，y=−3，x−y=5','["两项均为非负数，其和为零时两项都必须为零。","x−2=0，y+3=0，所以 x=2，y=−3。","x−y=2−(−3)=5。"]','[]',NULL);
INSERT INTO topics VALUES ('t24','4.3','立方根与开立方','每个实数都有一个立方根；正、负、零的立方根分别为正、负、零。','找一个数，使其立方等于被开方数；负号可以移到立方根外。','立方根只有一个；负数有实数立方根。');
INSERT INTO questions VALUES ('t24-example','t24','example',NULL,'计算题','求 −125 的立方根。','−5','["(−5)³=−125，所以 ∛(−125)=−5。"]','[]',NULL);
INSERT INTO questions VALUES ('t24-1','t24','practice','基础题','填空题','∛64=____。','4','["4³=64，所以 ∛64=4。"]','[]',NULL);
INSERT INTO questions VALUES ('t24-2','t24','practice','提高题','计算题','解方程 (2x−1)³=27。','x=2','["两边开立方得 2x−1=3。","2x=4，x=2。"]','[]',NULL);
INSERT INTO questions VALUES ('t24-3','t24','practice','压轴题','解答题','一个数的算术平方根为 a，立方根为 4，求原数及 a。','原数 64，a=8','["立方根为 4，所以原数为 4³=64。","a 是 64 的算术平方根，因此 a=√64=8，不能取 −8。"]','[]',NULL);
INSERT INTO topics VALUES ('t25','4.4','夹逼估算与比较大小','利用相邻完全平方数或立方数确定根式范围。','找相邻整数，再按要求逐位比较平方；负数比较需反向。','四舍五入与直接截取小数不同。');
INSERT INTO questions VALUES ('t25-example','t25','example',NULL,'解答题','√30 在哪两个相邻整数之间？','5 与 6','["25＜30＜36，即 5²＜30＜6²。","所以 5＜√30＜6。"]','[]',NULL);
INSERT INTO questions VALUES ('t25-1','t25','practice','基础题','选择题','√50 最接近的整数是（　）。','B','["7²=49，8²=64，√50 约为 7.07，最接近 7。"]','["6","7","8","9"]',NULL);
INSERT INTO questions VALUES ('t25-2','t25','practice','提高题','填空题','比较 −√7 与 −2.6：−√7____−2.6。','＜','["2.6²=6.76＜7，所以 2.6＜√7。","两数取相反数，不等号反向，−√7＜−2.6。"]','[]',NULL);
INSERT INTO questions VALUES ('t25-3','t25','practice','压轴题','解答题','设 √10 的整数部分为 a、小数部分为 b，求 a−b，并估计其在什么相邻整数之间。','6−√10，在 2 与 3 之间','["3＜√10＜4，所以 a=3、b=√10−3。","a−b=3−(√10−3)=6−√10。","由 3＜√10＜4，得 2＜6−√10＜3。"]','[]',NULL);
INSERT INTO topics VALUES ('t26','4.5','计算器开方与结果精度','开方后根据题意保留位数；中间计算应尽量保留精度，最后统一取近似值。','输入完整被开方数，检查数量级，再四舍五入。','近似值使用 ≈；不要把屏幕截断误当四舍五入。');
INSERT INTO questions VALUES ('t26-example','t26','example',NULL,'计算题','用计算器求 √2，结果保留两位小数。','≈1.41','["√2≈1.41421356。","第三位小数是 4，不进位，保留两位为 1.41。"]','[]',NULL);
INSERT INTO questions VALUES ('t26-1','t26','practice','基础题','填空题','计算器显示 √5≈2.2360679，保留两位小数为____。','2.24','["第三位小数为 6，第二位小数进 1，得 2.24。"]','[]',NULL);
INSERT INTO questions VALUES ('t26-2','t26','practice','提高题','计算题','用计算器求 ∛20，保留一位小数，并用整数立方检查结果范围。','≈2.7','["2³=8＜20＜27=3³，所以结果应在 2 与 3 之间。","∛20≈2.7144，保留一位小数得 2.7。"]','[]',NULL);
INSERT INTO questions VALUES ('t26-3','t26','practice','压轴题','解答题','正方形面积为 2 平方米，求周长，保留两位小数。说明先把边长保留两位再乘 4 是否一定得到同样结果。','周长约 5.66 米；提前舍入得到 5.64 米，有误差','["边长为 √2 米，周长为 4√2≈5.656854 米，四舍五入为 5.66 米。","若先把 √2 舍入为 1.41，再乘 4，得 5.64 米。","提前舍入会累计误差，应最后一步统一保留位数。"]','[]',NULL);
INSERT INTO topics VALUES ('t27','4.6','实数的数轴、绝对值与相反数','实数与数轴上的点一一对应；|a| 是到原点的距离。','先判断位置，再去绝对值；点间距离等于两坐标差的绝对值。','负数的绝对值是正数；非负数包含零。');
INSERT INTO questions VALUES ('t27-example','t27','example',NULL,'计算题','求 −√3 的相反数与绝对值。','均为 √3','["相反数是符号相反的数，所以为 √3。","−√3＜0，绝对值为 √3。"]','[]',NULL);
INSERT INTO questions VALUES ('t27-1','t27','practice','基础题','填空题','数轴上表示 −2 的点与表示 5 的点的距离为____。','7','["距离为 |5−(−2)|=7。"]','[]',NULL);
INSERT INTO questions VALUES ('t27-2','t27','practice','提高题','计算题','化简 |√5−3|+|√5−1|。','2','["因为 1＜√5＜3，第一项为 3−√5，第二项为 √5−1。","相加得 2。"]','[]',NULL);
INSERT INTO questions VALUES ('t27-3','t27','practice','压轴题','解答题','求所有满足 |x−2|+|x+1|=3 的实数 x。','−1≤x≤2','["两绝对值表示 x 到数轴上 2 和 −1 的距离。两端点距离为 3。","当 −1≤x≤2，距离和=(2−x)+(x+1)=3。","当 x＜−1，和=1−2x＞3；当 x＞2，和=2x−1＞3。","所以解集为 −1≤x≤2。"]','[]',NULL);
INSERT INTO topics VALUES ('t28','4.6','实数混合运算与化简','运算顺序是先乘方开方、后乘除、再加减；同类根式可合并。','先化简根式与绝对值，再按运算顺序计算。','√(a+b) 一般不等于 √a+√b。');
INSERT INTO questions VALUES ('t28-example','t28','example',NULL,'计算题','计算 √36+∛(−8)−|−3|。','1','["√36=6，∛(−8)=−2，|−3|=3。","原式=6−2−3=1。"]','[]',NULL);
INSERT INTO questions VALUES ('t28-1','t28','practice','基础题','计算题','计算 √49−√16+∛27。','6','["分别开方得 7、4、3。","原式=7−4+3=6。"]','[]',NULL);
INSERT INTO questions VALUES ('t28-2','t28','practice','提高题','计算题','计算 2√3+√12−√27。','√3','["√12=2√3，√27=3√3。","原式=2√3+2√3−3√3=√3。"]','[]',NULL);
INSERT INTO questions VALUES ('t28-3','t28','practice','压轴题','计算题','计算 (√3+1)(√3−1)+|√2−2|−√8。','4−3√2','["平方差公式得 (√3+1)(√3−1)=3−1=2。","√2＜2，所以 |√2−2|=2−√2；√8=2√2。","原式=2+2−√2−2√2=4−3√2。"]','[]',NULL);
INSERT INTO topics VALUES ('t29','5.1','有序数对与位置描述','平面位置通常用两个独立信息确定，有序数对中的先后顺序有约定。','先明确每个数代表什么，再按约定写坐标。','(a,b) 与 (b,a) 通常表示不同位置。');
INSERT INTO questions VALUES ('t29-example','t29','example',NULL,'解答题','座位用（列，排）表示，小明在第 3 列第 5 排，写出位置。','(3,5)','["约定第一项为列，第二项为排。","所以第 3 列第 5 排写作 (3,5)。"]','[]',NULL);
INSERT INTO questions VALUES ('t29-1','t29','practice','基础题','选择题','按（列，排）记位置，(4,2) 表示（　）。','A','["有序数对第一项 4 是列，第二项 2 是排。"]','["第4列第2排","第2列第4排","第4排","第2列"]',NULL);
INSERT INTO questions VALUES ('t29-2','t29','practice','提高题','填空题','按（列，排）记座位，从 (2,3) 向列号增大的方向移动 3 列，再向排号减小的方向移动 1 排，到达____。','(5,2)','["列号由 2 变为 2+3=5。","排号由 3 变为 3−1=2，所以为 (5,2)。"]','[]',NULL);
INSERT INTO questions VALUES ('t29-3','t29','practice','压轴题','解答题','方格中向右为列号增加、向上为行号增加。A=(1,2)，沿 A→B→C→D 运动：向右 4 格、向上 3 格、向左 2 格。求 D，并说明由 D 到 A 的最少格数（只沿格线）。','D=(3,5)，最少 5 格','["依次得 B=(5,2)、C=(5,5)、D=(3,5)。","回到 A 需列号减少 2、行号减少 3。","最少沿格线走 2+3=5 格，可以先左 2 再下 3 实现。"]','[]',NULL);
INSERT INTO topics VALUES ('t30','5.2','坐标轴、象限与点的坐标','四象限符号依次为 (+,+)、(−,+)、(−,−)、(+,−)；坐标轴上的点不属于任何象限。','先看横坐标，再看纵坐标；出现零要单独判断坐标轴。','横坐标为零在 y 轴上，纵坐标为零在 x 轴上。');
INSERT INTO questions VALUES ('t30-example','t30','example',NULL,'解答题','判断 A(−3,2)、B(0,−4) 的位置。','A 在第二象限；B 在 y 轴负半轴','["A 的横坐标负、纵坐标正，所以在第二象限。","B 的横坐标为 0、纵坐标负，所以在 y 轴负半轴，不属于象限。"]','[]',NULL);
INSERT INTO questions VALUES ('t30-1','t30','practice','基础题','选择题','点 (4,−2) 位于（　）。','D','["横坐标正、纵坐标负，位于第四象限。"]','["第一象限","第二象限","第三象限","第四象限"]',NULL);
INSERT INTO questions VALUES ('t30-2','t30','practice','提高题','填空题','点 P(a−2,3) 在 y 轴上，则 a=____。','2','["在 y 轴上，横坐标等于零，a−2=0，a=2。"]','[]',NULL);
INSERT INTO questions VALUES ('t30-3','t30','practice','压轴题','解答题','点 P(2a−1,a+2) 在第二象限，求 a 的取值范围；其中有几个整数？','−2＜a＜1/2；有 2 个整数（−1、0）','["第二象限要求 2a−1＜0 且 a+2＞0。","解得 a＜1/2 且 a＞−2，合并为 −2＜a＜1/2。","满足严格范围的整数为 −1、0，共 2 个。"]','[]',NULL);
INSERT INTO topics VALUES ('t31','5.2','到坐标轴的距离与参数','点 (x,y) 到 x 轴的距离为 |y|，到 y 轴的距离为 |x|。','距离给绝对值，再用象限确定符号。','距离不能为负；“到 x 轴”看的是纵坐标。');
INSERT INTO questions VALUES ('t31-example','t31','example',NULL,'计算题','点 A(−3,4) 到两坐标轴的距离分别是多少？','到 x 轴为 4；到 y 轴为 3','["到 x 轴看 |y|=4。","到 y 轴看 |x|=3。"]','[]',NULL);
INSERT INTO questions VALUES ('t31-1','t31','practice','基础题','填空题','点 (5,−7) 到 x 轴的距离为____。','7','["距离为纵坐标绝对值 |−7|=7。"]','[]',NULL);
INSERT INTO questions VALUES ('t31-2','t31','practice','提高题','解答题','点 P 在第三象限，到 x 轴距离为 2，到 y 轴距离为 6，求 P。','P(−6,−2)','["|y|=2，|x|=6。","第三象限两坐标都负，所以 P=(−6,−2)。"]','[]',NULL);
INSERT INTO questions VALUES ('t31-3','t31','practice','压轴题','解答题','点 P(a−1,2a+1) 到两坐标轴距离相等，求 P 的所有可能坐标。','(−3,−3) 或 (−1,1)','["等距条件为 |a−1|=|2a+1|。","若 a−1=2a+1，得 a=−2，P=(−3,−3)。","若 a−1=−(2a+1)，得 a=0，P=(−1,1)。"]','[]',NULL);
INSERT INTO topics VALUES ('t32','5.2','坐标中的线段与图形面积','同水平线上两点距离为横坐标差的绝对值；面积可用底×高或分割补形。','先利用平行坐标轴的边确定底和高，复杂图形分割。','面积取非负值；跨坐标轴时距离常为绝对值之和。');
INSERT INTO questions VALUES ('t32-example','t32','example',NULL,'计算题','A(−2,0)、B(4,0)、C(1,3)，求 △ABC 面积。','9','["AB 在 x 轴上，底长=4−(−2)=6。","C 到 x 轴距离为 3，面积=6×3÷2=9。"]','[]','{"points":{"A":[-2,0,-22,19],"B":[4,0,5,19],"C":[1,3],"O":[0,0,5,19]},"lines":[["A","B"],["B","C"],["C","A"]],"bounds":[-3,5,-1,4],"axes":true,"label":"坐标系中的 A(-2,0)、B(4,0)、C(1,3)"}');
INSERT INTO questions VALUES ('t32-1','t32','practice','基础题','填空题','A(1,2)、B(6,2)，则 AB=____。','5','["两点纵坐标相同，AB=|6−1|=5。"]','[]',NULL);
INSERT INTO questions VALUES ('t32-2','t32','practice','提高题','计算题','长方形相邻三个顶点为 A(−2,−1)、B(4,−1)、C(4,3)，求第四顶点及面积。','D(−2,3)，面积 24','["第四顶点与 A 横坐标相同、与 C 纵坐标相同，D=(−2,3)。","长=6，宽=4，所以面积为 24。"]','[]',NULL);
INSERT INTO questions VALUES ('t32-3','t32','practice','压轴题','解答题','A(−2,0)、B(4,0)，P 在直线 x=1 上。若 △ABP 面积为 15，求 P 的所有坐标。','(1,5) 或 (1,−5)','["底 AB=6，设 P=(1,y)，高为 |y|。","面积=6|y|÷2=15，得 |y|=5。","所以 y=±5，P=(1,5) 或 (1,−5)。"]','[]',NULL);
INSERT INTO topics VALUES ('t33','5.3','轴对称与坐标变化','关于 x 轴对称：(x,−y)；关于 y 轴对称：(−x,y)。','保留与轴平行方向的坐标，改变垂直方向坐标的符号。','关于 x 轴对称改变的是纵坐标。');
INSERT INTO questions VALUES ('t33-example','t33','example',NULL,'解答题','点 A(−2,3) 关于 x 轴、y 轴的对称点分别是什么？','(−2,−3)；(2,3)','["关于 x 轴，横坐标不变、纵坐标变号，得 (−2,−3)。","关于 y 轴，纵坐标不变、横坐标变号，得 (2,3)。"]','[]',NULL);
INSERT INTO questions VALUES ('t33-1','t33','practice','基础题','选择题','点 (3,−4) 关于 y 轴的对称点是（　）。','B','["横坐标变号、纵坐标不变，所以为 (−3,−4)。"]','["(3,4)","(−3,−4)","(−3,4)","(4,−3)"]',NULL);
INSERT INTO questions VALUES ('t33-2','t33','practice','提高题','计算题','A(a+1,3)、B(−4,b−2) 关于 y 轴对称，求 a、b。','a=3，b=5','["关于 y 轴对称要求 a+1=4，3=b−2。","分别得 a=3，b=5。"]','[]',NULL);
INSERT INTO questions VALUES ('t33-3','t33','practice','压轴题','解答题','P(2,−3) 先关于 x 轴对称，再关于 y 轴对称，得到 Q。求 Q 与 PQ 的长度，并比较交换两次对称的顺序是否改变 Q。','Q(−2,3)，PQ=2√13；交换顺序结果不变','["先关于 x 轴得 (2,3)，再关于 y 轴得 Q=(−2,3)。","水平距离 4、竖直距离 6，由勾股定理得 PQ=√(16+36)=2√13。","交换顺序得 (−2,−3)→(−2,3)，结果相同。"]','[]',NULL);
INSERT INTO topics VALUES ('t34','6.1','函数判定与变量关系','在一个变化过程中，对于 x 的每一个允许值，y 都有唯一确定的值，则 y 是 x 的函数。','从自变量出发检查唯一性，允许多个 x 对应同一个 y。','一个 x 不能对应多个 y；不同 x 可以对应同一个 y。');
INSERT INTO questions VALUES ('t34-example','t34','example',NULL,'解答题','关系 y=x² 中，y 是 x 的函数吗？说明 x=2、x=−2 对应同一 y 是否矛盾。','是，不矛盾','["每给定一个实数 x，其平方唯一，所以 y 是 x 的函数。","2 与 −2 都对应 4，允许不同 x 对应同一个 y，不影响唯一性。"]','[]',NULL);
INSERT INTO questions VALUES ('t34-1','t34','practice','基础题','选择题','下列哪种对应使 y 不是 x 的函数？','C','["函数要求一个 x 对应唯一 y。C 中 x=1 同时对应 2、3，违反定义。"]','["每个 x 都对应 y=5","y=2x","x=1 时 y 可取 2 或 3","y=x+1"]',NULL);
INSERT INTO questions VALUES ('t34-2','t34','practice','提高题','填空题','水箱有水 80 升，每分钟流出 5 升，流出 t 分钟后的水量为 V。V=____，t 的实际范围为____。','80−5t；0≤t≤16','["剩余量=初始量−流出量，所以 V=80−5t。","时间非负，且水量不能为负：80−5t≥0，得 0≤t≤16。"]','[]',NULL);
INSERT INTO questions VALUES ('t34-3','t34','practice','压轴题','解答题','长方形周长为 20，长为 x、宽为 y，且长不小于宽。写出 y 与 x 的关系及 x 的范围。','y=10−x，5≤x＜10','["由 2(x+y)=20，得 y=10−x。","宽为正数要求 x＜10；长不小于宽，x≥10−x，得 x≥5。","合并得 5≤x＜10；每个允许的 x 都有唯一的 y。"]','[]',NULL);
INSERT INTO topics VALUES ('t35','6.1','函数表示与读图读表','函数可用表达式、表格、图象表示；读图要同时看坐标轴含义与单位。','先读横纵轴，再读变化率、特殊点与分段过程。','水平线段表示纵量不变，并不必然意味着物体静止，要看纵轴含义。');
INSERT INTO questions VALUES ('t35-example','t35','example',NULL,'解答题','路程表给出 t（时）=0、1、2、3，对应 s（千米）=0、60、120、180。若匀速行驶，写出 s 关于 t 的关系。','s=60t','["每增加 1 小时，路程增加 60 千米，速度为 60 千米/时。","从 0 出发，所以 s=60t。"]','[]',NULL);
INSERT INTO questions VALUES ('t35-1','t35','practice','基础题','填空题','函数 y=3x−1，当 x=4 时，y=____。','11','["代入得 y=3×4−1=11。"]','[]',NULL);
INSERT INTO questions VALUES ('t35-2','t35','practice','提高题','解答题','某人距家距离随时间变化：0～1 时从 0 增至 4 千米；1～1.5 时保持 4；1.5～2.5 时从 4 降至 0，各运动段均匀速。描述过程及总路程。','外出 4 千米，停留半小时，再返回；总路程 8 千米','["第一段用 1 小时远离家 4 千米。","第二段距离不变半小时；按题目路线可理解为原处停留。","第三段用 1 小时返回家，路程 4 千米；总路程=4+4=8 千米。"]','[]',NULL);
INSERT INTO questions VALUES ('t35-3','t35','practice','压轴题','解答题','水箱进水记录：t=0、2、5 分钟时，水量分别为 10、18、30 升。已知匀速进水，求水量表达式，以及达到 70 升所需时间。','V=4t+10；15 分钟','["前两分钟增加 8 升，速度为 4 升/分钟；2～5 分钟增加 12 升，同样为 4 升/分钟。","初始 10 升，所以 V=4t+10。","令 4t+10=70，解得 t=15 分钟。"]','[]',NULL);
INSERT INTO topics VALUES ('t36','6.2','一次函数与正比例函数的识别','y=kx+b（k≠0）是一次函数；b=0 时为正比例函数。','检查 x 的次数为 1、系数非零，再看常数项。','k=0 时是常值函数，不是一次函数。');
INSERT INTO questions VALUES ('t36-example','t36','example',NULL,'解答题','判断 y=−2x+3 与 y=5x 是否为一次函数、正比例函数。','二者都是一次函数；只有 y=5x 是正比例函数','["两式中 x 次数为 1，系数分别为 −2、5，均非零。","只有第二式常数项为 0，故只有 y=5x 是正比例函数。"]','[]',NULL);
INSERT INTO questions VALUES ('t36-1','t36','practice','基础题','选择题','下列是一次函数但不是正比例函数的是（　）。','B','["y=3x+2 的 k=3≠0、b=2≠0，满足要求。"]','["y=3x","y=3x+2","y=x²","y=3"]',NULL);
INSERT INTO questions VALUES ('t36-2','t36','practice','提高题','填空题','y=(m−2)x+5 为一次函数时，m 应满足____。','m≠2','["一次项系数不能为 0，所以 m−2≠0，得 m≠2。"]','[]',NULL);
INSERT INTO questions VALUES ('t36-3','t36','practice','压轴题','解答题','y=(m²−4)x+(m−2)。分别求它为一次函数、正比例函数时 m 的条件。','一次函数：m≠±2；不存在使它为正比例函数的 m','["一次函数要求 m²−4≠0，所以 m≠2 且 m≠−2。","正比例函数还需 m−2=0，得 m=2，但此时 x 的系数也为 0。","两个条件矛盾，故不存在这样的 m。"]','[]',NULL);
INSERT INTO topics VALUES ('t37','6.3','描点作图与坐标轴交点','一次函数的图象为直线；确定两个不同点即可画出。','常用 x=0、y=0 求坐标轴交点，再连线。','直线应向两端延伸；实际应用中则受自变量范围限制。');
INSERT INTO questions VALUES ('t37-example','t37','example',NULL,'作图题','画出 y=−2x+4 的图象，写出与两坐标轴的交点。','与 x 轴交于 (2,0)，与 y 轴交于 (0,4)','["x=0 时 y=4，得到 (0,4)。","y=0 时 −2x+4=0，x=2，得到 (2,0)。","在坐标系中描出两点，过两点作直线。"]','[]','{"points":{"A":[2,0,6,19],"B":[0,4],"O":[0,0,-15,19]},"graph":[[-2,4,-0.5,2.5]],"bounds":[-1,4,-2,6],"axes":true,"label":"直线 y=-2x+4，与两坐标轴交于 A(2,0)、B(0,4)"}');
INSERT INTO questions VALUES ('t37-1','t37','practice','基础题','填空题','y=3x−6 与 y 轴的交点为____。','(0,−6)','["y 轴上 x=0，代入得 y=−6，交点为 (0,−6)。"]','[]',NULL);
INSERT INTO questions VALUES ('t37-2','t37','practice','提高题','计算题','求 y=−x+6 与两坐标轴围成的三角形面积。','18','["与坐标轴交点为 (6,0)、(0,6)。","以两个截距为直角边，面积=6×6÷2=18。"]','[]',NULL);
INSERT INTO questions VALUES ('t37-3','t37','practice','压轴题','解答题','直线 y=kx+6 与 x 轴交于 A，与 y 轴交于 B，△OAB 面积为 9，求 k 的所有可能值。','k=2 或 −2','["B=(0,6)，设 A=(a,0)。面积为 |a|×6÷2=9，得 |a|=3。","当 a=3，0=3k+6，得 k=−2。","当 a=−3，0=−3k+6，得 k=2。"]','[]',NULL);
INSERT INTO topics VALUES ('t38','6.3','增减性、象限与参数','k＞0 时 y 随 x 增大而增大；k＜0 时减小。b 决定与 y 轴交点的位置。','从倾斜方向确定 k 的符号，从纵轴交点确定 b 的符号。','增减性由 k 决定，不由 b 决定。');
INSERT INTO questions VALUES ('t38-example','t38','example',NULL,'解答题','y=−3x+2 是增函数还是减函数？当 x 从 1 增加到 4，y 如何变化？','减函数；y 从 −1 降到 −10','["k=−3＜0，所以 y 随 x 增大而减小。","x=1 时 y=−1；x=4 时 y=−10，减少 9。"]','[]',NULL);
INSERT INTO questions VALUES ('t38-1','t38','practice','基础题','选择题','下列函数中 y 随 x 增大而增大的是（　）。','C','["只有 y=3x−8 的 k=3＞0，其余斜率都为负。"]','["y=−x+4","y=−2x","y=3x−8","y=−5x−1"]',NULL);
INSERT INTO questions VALUES ('t38-2','t38','practice','提高题','填空题','函数 y=(2m−4)x+1 中，y 随 x 增大而减小，则 m____。','＜2','["斜率 2m−4＜0，解得 m＜2。"]','[]',NULL);
INSERT INTO questions VALUES ('t38-3','t38','practice','压轴题','解答题','一次函数 y=(m−1)x+m+2 的图象经过第一、二、三象限，求 m 的范围。','m＞1','["经过第一、二、三象限的直线斜率为正，且 y 轴截距为正。","因此 m−1＞0 且 m+2＞0，分别得 m＞1、m＞−2。","同时满足时 m＞1。"]','[]',NULL);
INSERT INTO topics VALUES ('t39','6.4','待定系数法确定表达式','已知两点坐标可代入 y=kx+b，解方程组求 k、b。','先写一般式，再代入两个独立条件，最后回代核验。','两个点不能重合；同一竖直线上两点不能确定 y 关于 x 的一次函数。');
INSERT INTO questions VALUES ('t39-example','t39','example',NULL,'计算题','一次函数经过 (1,3)、(3,7)，求表达式。','y=2x+1','["代入得 k+b=3、3k+b=7。","相减得 2k=4，k=2，再得 b=1。","所以 y=2x+1，代入两点都成立。"]','[]',NULL);
INSERT INTO questions VALUES ('t39-1','t39','practice','基础题','填空题','正比例函数经过 (2,6)，其表达式为____。','y=3x','["设 y=kx，代入得 6=2k，k=3。"]','[]',NULL);
INSERT INTO questions VALUES ('t39-2','t39','practice','提高题','计算题','直线经过 (0,−2)，并与直线 y=3x+1 平行，求表达式。','y=3x−2','["平行直线斜率相同，所以 k=3。","经过 (0,−2)，得 b=−2，因此 y=3x−2。"]','[]',NULL);
INSERT INTO questions VALUES ('t39-3','t39','practice','压轴题','解答题','直线经过 A(−1,5)、B(2,−1)。求表达式；若点 P(t,2t+1) 也在直线上，求 P。','y=−2x+3；P(1/2,2)','["代入两点得 −k+b=5、2k+b=−1，相减得 3k=−6，k=−2，b=3。","P 满足 2t+1=−2t+3，解得 t=1/2。","纵坐标 2t+1=2，所以 P=(1/2,2)。"]','[]',NULL);
INSERT INTO topics VALUES ('t40','6.5','一次函数与方程、不等式','两直线交点对应两个函数值相等；图象的上下位置对应函数值大小。','先求相等时的分界点，再检验两侧大小，结合实际范围。','只求交点不能直接完成方案比较，还需讨论两侧。');
INSERT INTO questions VALUES ('t40-example','t40','example',NULL,'计算题','求 y=2x+1 与 y=−x+7 的交点。','(2,5)','["令 2x+1=−x+7，得 3x=6，x=2。","代入 y=5，所以交点为 (2,5)。"]','[]',NULL);
INSERT INTO questions VALUES ('t40-1','t40','practice','基础题','填空题','函数 y=3x−6 中，当 y=0 时 x=____。','2','["3x−6=0，解得 x=2。"]','[]',NULL);
INSERT INTO questions VALUES ('t40-2','t40','practice','提高题','解答题','何时函数 y₁=2x+3 的值大于 y₂=−x+9 的值？','x＞2','["列不等式 2x+3＞−x+9。","3x＞6，解得 x＞2，对应第一条直线在第二条上方。"]','[]',NULL);
INSERT INTO questions VALUES ('t40-3','t40','practice','压轴题','解答题','直线 y₁=x+2、y₂=−2x+8 相交于 P，分别与 x 轴交于 A、B。求 △PAB 面积。','12','["交点满足 x+2=−2x+8，x=2，y=4，P=(2,4)。","A=(−2,0)，B=(4,0)，所以 AB=6。","高为 P 到 x 轴距离 4，面积=6×4÷2=12。"]','[]','{"points":{"A":[-2,0,-20,19],"B":[4,0,6,19],"P":[2,4],"O":[0,0,5,19]},"lines":[["A","B"],["A","P"],["P","B"]],"bounds":[-3,5,-1,5],"axes":true,"label":"两直线交点 P(2,4)，与 x 轴交于 A(-2,0)、B(4,0)"}');
INSERT INTO topics VALUES ('t41','6.5','计费与方案比较','总费用常由固定费用与按量费用组成，按规则建立分段表达式。','写清使用量范围，求费用相等点，再判断区间内哪个便宜。','免费额度、起步价等会使表达式分段。');
INSERT INTO questions VALUES ('t41-example','t41','example',NULL,'解答题','两种套餐：甲固定费 20 元、每次 2 元；乙无固定费、每次 3 元。使用 x 次时，何时同价？','20 次，同为 60 元','["甲费为 20+2x，乙费为 3x。","令 20+2x=3x，得 x=20，费用 60 元。"]','[]',NULL);
INSERT INTO questions VALUES ('t41-1','t41','practice','基础题','填空题','打印店收装订费 5 元，每页 0.2 元。打印并装订 x 页的费用 y=____元。','0.2x+5','["总费=页数费用+固定装订费，所以 y=0.2x+5。"]','[]',NULL);
INSERT INTO questions VALUES ('t41-2','t41','practice','提高题','解答题','甲方案每月 30 元另加每次 1 元，乙方案每月 10 元另加每次 2 元。分别说明使用多少次时哪种便宜。','少于 20 次选乙；20 次同价；多于 20 次选甲','["设次数为非负整数 x，甲=30+x，乙=10+2x。","差值甲−乙=20−x。","x＜20 时差为正，乙便宜；x=20 同价；x＞20 甲便宜。"]','[]',NULL);
INSERT INTO questions VALUES ('t41-3','t41','practice','压轴题','解答题','甲打印店每页 0.4 元；乙收 12 元会员费，前 20 页免费，超过部分每页 0.2 元。一次打印 x 页（正整数），比较两店费用。','1～39 页甲便宜；40 页同价；41 页起乙便宜','["甲费为 0.4x。乙在 1≤x≤20 时为 12 元，此时甲至多 8 元，甲便宜。","x＞20 时，乙费=12+0.2(x−20)=0.2x+8。","相等时 0.4x=0.2x+8，得 x=40。","结合整数范围，1～39 页甲便宜，40 页同价，41 页及以上乙便宜。"]','[]',NULL);
INSERT INTO topics VALUES ('t42','6.5','行程问题与分段函数','位置=初始位置+速度×时间；方向不同用带符号的速度表示。','统一时间起点与位置原点，区分位置、路程和两人距离。','晚出发的运动时间应减去等待时长。');
INSERT INTO questions VALUES ('t42-example','t42','example',NULL,'解答题','甲乙相距 120 千米，同时相向而行，速度分别为 40、20 千米/时，几小时相遇？','2 小时','["相遇前距离 D=120−(40+20)t=120−60t。","D=0 时 t=2 小时。"]','[]',NULL);
INSERT INTO questions VALUES ('t42-1','t42','practice','基础题','填空题','匀速行驶速度为 60 千米/时，t 小时路程 s=____。','60t','["路程=速度×时间，所以 s=60t。"]','[]',NULL);
INSERT INTO questions VALUES ('t42-2','t42','practice','提高题','解答题','甲以 4 千米/时从 A 地出发，乙半小时后从 A 地同向出发，速度为 6 千米/时。乙出发多久后追上甲？','1 小时','["设乙出发 t 小时，甲已运动 t+0.5 小时。","追上时 6t=4(t+0.5)，得 2t=2，t=1。"]','[]',NULL);
INSERT INTO questions VALUES ('t42-3','t42','practice','压轴题','解答题','A、B 两地相距 12 千米。甲从 A 向 B 匀速走，速度 4 千米/时；乙同时从 B 向 A 走，速度 2 千米/时。两人到目的地即停。求出发后 0～3 小时内两人距离为 3 千米的时刻。','1.5 小时和 2.5 小时','["以 A 为原点、A→B 为正，0≤t≤3 时甲位置为 4t，乙为 12−2t。","距离 D=|4t−(12−2t)|=|6t−12|。","令 D=3，得 6t−12=3 或 −3，分别 t=2.5 或 1.5。","两个时刻都在 0～3 小时内，均成立。"]','[]',NULL);
INSERT INTO topics VALUES ('t43','6.5','函数与几何综合、动点面积','把动点坐标代入面积关系，以自变量表示底或高。','先限定运动范围，再列面积式；面积中的距离需非负。','运动范围与代数解必须同时满足。');
INSERT INTO questions VALUES ('t43-example','t43','example',NULL,'解答题','A(0,4)、B(6,0)，P(t,0) 在线段 OB 上，求 △AOP 面积 S 关于 t 的关系。','S=2t，0≤t≤6','["底 OP=t，高为 A 到 x 轴距离 4。","面积 S=t×4÷2=2t；P 在线段 OB 上，故 0≤t≤6。"]','[]',NULL);
INSERT INTO questions VALUES ('t43-1','t43','practice','基础题','计算题','A(0,6)、P(4,0)，求 △OAP 的面积。','12','["两直角边长为 6、4。","面积=6×4÷2=12。"]','[]',NULL);
INSERT INTO questions VALUES ('t43-2','t43','practice','提高题','解答题','A(0,6)、B(8,0)，P(t,0) 在线段 OB 上。若 △APB 面积为 9，求 P。','P(5,0)','["PB=8−t，高为 6。","S=6(8−t)÷2=9，得 8−t=3，t=5。","5 在 [0,8] 内，所以 P=(5,0)。"]','[]',NULL);
INSERT INTO questions VALUES ('t43-3','t43','practice','压轴题','解答题','直线 y=−x+6 与坐标轴交于 A(6,0)、B(0,6)。P(t,6−t) 在线段 AB 上。求 △OPB 面积等于 △OPA 面积两倍时 P 的坐标。','P(4,2)','["△OPB 以 OB 为底，面积 S₁=6t÷2=3t。","△OPA 以 OA 为底，面积 S₂=6(6−t)÷2=18−3t。","S₁=2S₂，得 3t=36−6t，t=4。","0≤4≤6，P=(4,2)。"]','[]',NULL);
INSERT INTO topics VALUES ('t44','1.0','三角形单元综合','串联三边关系、内外角、全等判定与对应边角。','先列目标，再选三角形，按“条件—判定—结论”写证明。','公共边与公共角也要明确写出。');
INSERT INTO questions VALUES ('t44-example','t44','example',NULL,'证明题','△ABC 中 AB=AC，D 是 BC 中点。证明 AD 平分 ∠BAC。','∠BAD=∠CAD','["AB=AC，BD=CD，AD 公共。","△ABD≌△ACD（SSS），所以 ∠BAD=∠CAD。"]','[]','{"points":{"A":[4,6],"B":[0,0,-16,16],"C":[8,0,6,16],"D":[4,0,6,16]},"lines":[["A","B"],["B","C"],["C","A"],["A","D"]],"label":"三角形 ABC，D 为底边 BC 的中点"}');
INSERT INTO questions VALUES ('t44-1','t44','practice','基础题','计算题','△ABC 中 AB=AC，∠A=40°。D 为 BC 中点，求 ∠BAD、∠ADB。','20°；90°','["由 SSS 得 △ABD≌△ACD，所以 ∠BAD=∠CAD=20°。","∠ADB=∠ADC，且两角和为 180°，故 ∠ADB=90°。"]','[]','{"points":{"A":[4,6],"B":[0,0,-16,16],"C":[8,0,6,16],"D":[4,0,6,16]},"lines":[["A","B"],["B","C"],["C","A"],["A","D"]],"label":"三角形 ABC，D 为底边 BC 的中点"}');
INSERT INTO questions VALUES ('t44-2','t44','practice','提高题','证明题','AB、CD 相交于 O，OA=OB、OC=OD。证明 AC∥BD。','AC∥BD','["两边及对顶角相等，△AOC≌△BOD（SAS）。","所以 ∠OAC=∠OBD，这是一组内错角，故 AC∥BD。"]','[]',NULL);
INSERT INTO questions VALUES ('t44-3','t44','practice','压轴题','证明题','△ABC 中 AB=AC，D、E 分别在 AB、AC 上且 BD=CE，BE、CD 交于 O。证明 OB=OC。','OB=OC','["AD=AB−BD，AE=AC−CE，所以 AD=AE。","△ABE≌△ACD（SAS），故 ∠ABE=∠ACD。","由 AB=AC 得 ∠ABC=∠ACB，两边分别减去相等的角，得 ∠OBC=∠OCB。","△OBC 等角对等边，故 OB=OC。"]','[]',NULL);
INSERT INTO topics VALUES ('t45','2.0','轴对称单元综合','将轴对称、线段垂直平分线、角平分线与等腰性质结合。','先把图形对称关系转化为等边或等角，再推理。','等距对象要分清端点与直线。');
INSERT INTO questions VALUES ('t45-example','t45','example',NULL,'解答题','等腰 △ABC 中 AB=AC=10，D 是 BC 中点，BC=12。说明 AD 为什么是对称轴所在直线。','直线 AD 垂直平分 BC，并交换 B、C','["由等腰三角形性质，AD 垂直且平分 BC。","A 在轴上不动，B、C 互为对称点，因此两侧三角形完全重合。"]','[]','{"points":{"A":[4,6],"B":[0,0,-16,16],"C":[8,0,6,16],"D":[4,0,6,16]},"lines":[["A","B"],["B","C"],["C","A"],["A","D"]],"label":"三角形 ABC，D 为底边 BC 的中点"}');
INSERT INTO questions VALUES ('t45-1','t45','practice','基础题','填空题','点 P 在 AB 的垂直平分线上，PA=7，则 PB=____。','7','["垂直平分线上的点到两端点距离相等。"]','[]',NULL);
INSERT INTO questions VALUES ('t45-2','t45','practice','提高题','计算题','等腰三角形一个角为 100°，求其余两角，并说明 100° 不能是底角的理由。','40°、40°','["若 100° 为底角，则两个底角和为 200°，超过内角和，不可能。","故 100° 为顶角，其余两角均为 (180°−100°)÷2=40°。"]','[]',NULL);
INSERT INTO questions VALUES ('t45-3','t45','practice','压轴题','证明题','△ABC 中 AB=AC，D 是 BC 中点。P 在线段 AD 上，过 P 分别作 PM⊥AB、PN⊥AC。证明 PM=PN 且 BM=CN。','PM=PN，BM=CN','["AD 平分 ∠BAC，所以 PM=PN。","Rt△APM 与 Rt△APN 斜边 AP 公共、直角边 PM=PN，由 HL 全等，故 AM=AN。","P 在线段 AD 上，垂足 M、N 位于边 AB、AC 上；因此 BM=AB−AM=AC−AN=CN。"]','[]',NULL);
INSERT INTO topics VALUES ('t46','3.0','勾股定理单元综合','结合三边判断、作高分割、面积与实际距离。','确定直角关系，再列平方关系；用面积找到不同高之间的联系。','求出的边长、时间、距离应满足实际范围。');
INSERT INTO questions VALUES ('t46-example','t46','example',NULL,'解答题','直角三角形两直角边为 9、12，求斜边及斜边上的高。','斜边 15，高 36/5','["斜边=√(81+144)=15。","面积=9×12÷2=54；也等于 15h÷2。","因此 h=108/15=36/5。"]','[]',NULL);
INSERT INTO questions VALUES ('t46-1','t46','practice','基础题','选择题','三边为 9、12、15 的三角形是（　）。','B','["9²+12²=81+144=225=15²，所以为直角三角形。"]','["等边三角形","直角三角形","等腰三角形","无法判断"]',NULL);
INSERT INTO questions VALUES ('t46-2','t46','practice','提高题','计算题','等腰三角形腰长 10，底长 12，求面积与周长。','面积 48；周长 32','["高平分底边，半底为 6，高=√(100−36)=8。","面积=12×8÷2=48，周长=10+10+12=32。"]','[]',NULL);
INSERT INTO questions VALUES ('t46-3','t46','practice','压轴题','解答题','三角形三边为 10、17、21，长 21 的边上的高落在该边内部。求这条高和面积。','高 8，面积 84','["设高的垂足将长 21 的边分为 x、21−x，前一段邻边为 10。","x²+h²=100，(21−x)²+h²=289。","相减得 441−42x=189，x=6，h²=64，h=8。","面积=21×8÷2=84。"]','[]',NULL);
INSERT INTO topics VALUES ('t47','4.0','实数单元综合','综合平方根、立方根、绝对值、估算与混合运算。','先判断符号与范围，后化简计算；结果尽量保留准确值。','算术平方根不能随意添加正负号。');
INSERT INTO questions VALUES ('t47-example','t47','example',NULL,'计算题','计算 √64+∛(−27)−|1−√2|。','6−√2','["√64=8，∛(−27)=−3。","1−√2＜0，所以绝对值为 √2−1。","原式=8−3−√2+1=6−√2。"]','[]',NULL);
INSERT INTO questions VALUES ('t47-1','t47','practice','基础题','填空题','−8 的立方根与 9 的算术平方根的和为____。','1','["∛(−8)=−2，√9=3，两者之和为 1。"]','[]',NULL);
INSERT INTO questions VALUES ('t47-2','t47','practice','提高题','解答题','求满足 x²=36 且 x＜0 的 x，再计算 |x−1|。','x=−6，|x−1|=7','["x²=36 的解为 ±6，由 x＜0 取 x=−6。","|x−1|=|−7|=7。"]','[]',NULL);
INSERT INTO questions VALUES ('t47-3','t47','practice','压轴题','解答题','已知 √(a−1)+|b+2|=0，求 a、b，并计算 √((a+b)²)+∛(b³)。','a=1，b=−2，结果为 −1','["两个非负项之和为零，各自为零，所以 a=1、b=−2。","a+b=−1，√((a+b)²)=|−1|=1。","∛(b³)=b=−2，结果为 1−2=−1。"]','[]',NULL);
INSERT INTO topics VALUES ('t48','5.0','位置与坐标单元综合','把象限、距离、轴对称、勾股定理和面积串联起来。','先标坐标，再选距离或面积公式，完整保留符号信息。','坐标与距离不是同一个量。');
INSERT INTO questions VALUES ('t48-example','t48','example',NULL,'解答题','A(−3,4) 关于 x 轴的对称点为 B，求 B 及 AB。','B(−3,−4)，AB=8','["关于 x 轴纵坐标变号，B=(−3,−4)。","两点横坐标相同，距离为 |4−(−4)|=8。"]','[]',NULL);
INSERT INTO questions VALUES ('t48-1','t48','practice','基础题','填空题','点 (−4,−3) 到原点的距离为____。','5','["与坐标轴构成两直角边长 4、3 的直角三角形。","距离=√(16+9)=5。"]','[]',NULL);
INSERT INTO questions VALUES ('t48-2','t48','practice','提高题','计算题','A(−3,2)、B(3,2)，O 为原点，求 △OAB 面积，并判断 A、B 关于哪条轴对称。','面积 6；关于 y 轴对称','["AB 长为 6，O 到直线 y=2 的距离为 2，面积=6×2÷2=6。","A、B 横坐标互为相反数、纵坐标相等，关于 y 轴对称。"]','[]',NULL);
INSERT INTO questions VALUES ('t48-3','t48','practice','压轴题','解答题','A(−2,3)，B 为 A 关于 y 轴的对称点，C 为 A 关于 x 轴的对称点。求 △ABC 面积及 BC。','面积 12，BC=2√13','["B=(2,3)，C=(−2,−3)。","AB=4，AC=6，AB⊥AC，所以面积=4×6÷2=12。","BC=√(4²+6²)=√52=2√13。"]','[]',NULL);
INSERT INTO topics VALUES ('t49','6.0','一次函数单元综合','贯通待定系数、交点、面积、方案选择与取值范围。','先建立表达式，再以交点或端点作为分界进行讨论。','实际条件与数学范围必须同时满足。');
INSERT INTO questions VALUES ('t49-example','t49','example',NULL,'解答题','一次函数经过 (0,4)、(2,0)，求表达式及图象与两坐标轴围成的面积。','y=−2x+4，面积 4','["由 (0,4) 得 b=4；由 (2,0) 得 2k+4=0，k=−2。","两坐标轴截距长度为 2、4，面积为 2×4÷2=4。"]','[]',NULL);
INSERT INTO questions VALUES ('t49-1','t49','practice','基础题','填空题','y=2x−4 的图象与 x 轴交于____。','(2,0)','["令 y=0，2x−4=0，x=2。"]','[]',NULL);
INSERT INTO questions VALUES ('t49-2','t49','practice','提高题','解答题','两家租车方案分别为 y₁=100+20x、y₂=40x（x 为正整数小时）。比较何时哪家便宜。','1～4 小时选第二家；5 小时同价；6 小时起选第一家','["相等时 100+20x=40x，x=5。","差 y₁−y₂=100−20x，小于 5 时为正，大于 5 时为负。","结合正整数小时得所述范围。"]','[]',NULL);
INSERT INTO questions VALUES ('t49-3','t49','practice','压轴题','解答题','直线 l 经过 (0,6)、(3,0)，与 y=x 交于 P。A 为 l 与 x 轴交点，B 为 l 与 y 轴交点，求 P 和 △OPA、△OPB 的面积比。','P(2,2)，面积比 1∶2','["由两点得 l：y=−2x+6。","联立 y=x，得 x=2、y=2，即 P=(2,2)。","A=(3,0)，B=(0,6)。S△OPA=3×2÷2=3，S△OPB=6×2÷2=6。","所以面积比为 1∶2。"]','[]',NULL);
CREATE INDEX questions_by_topic ON questions(topic_id);
CREATE INDEX questions_by_difficulty_type ON questions(difficulty,question_type);
COMMIT;
